# Generated by Django 6.0.4 on 2026-05-06 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyerprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='farmerprofile',
            options={},
        ),
        migrations.RenameField(
            model_name='buyerprofile',
            old_name='address',
            new_name='delivery_address',
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='farm_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='specialty',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='EnquiryReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('enquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='market.enquiry')),
            ],
        ),
    ]
