# Generated by Django 6.0.4 on 2026-05-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_rating_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='emoji',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
