# Generated by Django 6.0.4 on 2026-05-13 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_crop_emoji'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery', models.CharField(choices=[('pickup', 'Self Pickup'), ('delivery', 'Home Delivery')], max_length=20)),
                ('payment', models.CharField(choices=[('cod', 'Cash on Delivery'), ('upi', 'UPI')], max_length=20)),
                ('address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='market.buyerprofile')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='market.crop')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='market.farmerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
