# Generated by Django 6.0.4 on 2026-05-14 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='market.buyerprofile')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_carts', to='market.crop')),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('buyer', 'crop')},
            },
        ),
    ]
