# Generated by Django 6.0.4 on 2026-05-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_cart'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='enquiryreply',
            name='enquiry',
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='crop',
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='farmer_note',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='Enquiry',
        ),
        migrations.DeleteModel(
            name='EnquiryReply',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
