# Generated by Django 6.0.4 on 2026-05-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_alter_chatroom_unique_together_remove_chatroom_buyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
