# Generated by Django 6.0.4 on 2026-05-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_alter_crop_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_seen',
            field=models.BooleanField(default=False),
        ),
    ]
