# Generated by Django 6.0.4 on 2026-05-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_order_buyer_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='farmer_seen',
            field=models.BooleanField(default=False),
        ),
    ]
