# Generated by Django 6.0.4 on 2026-05-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_order_farmer_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price per unit in Indian Rupees', max_digits=10),
        ),
    ]
